"""added session_decisions table

Revision ID: 46ef651ce216
Revises: a95ecd118b35
Create Date: 2026-05-30 22:11:08.550081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import pgvector
import uuid
import json

# revision identifiers, used by Alembic.
revision: str = '46ef651ce216'
down_revision: Union[str, Sequence[str], None] = 'a95ecd118b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # create project_decisions table (for fresh DBs) if it doesn't already exist
    conn = op.get_bind()
    table_exists = conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='project_decisions'")).fetchone()
    if not table_exists:
        op.create_table(
            'project_decisions',
            sa.Column('id', sa.String(length=36), primary_key=True),
            sa.Column('session_id', sa.String(length=36), sa.ForeignKey('sessions.id', ondelete='CASCADE'), nullable=False),
            sa.Column('project_id', sa.String(length=36), sa.ForeignKey('projects.id', ondelete='CASCADE'), nullable=False),
            sa.Column('user_id', sa.String(length=36), nullable=False),
            sa.Column('decision_text', sa.Text(), nullable=False),
            sa.Column('decision_order', sa.Integer(), nullable=False, server_default='1'),
            sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
            sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        )

    # migrate existing JSON decisions into new table
    rows = conn.execute(sa.text("SELECT id, project_id, user_id, decisions FROM sessions")).fetchall()
    for r in rows:
        if not r['decisions']:
            continue
        try:
            dec_list = json.loads(r['decisions']) if isinstance(r['decisions'], (str, bytes)) else r['decisions']
        except Exception:
            dec_list = []
        for idx, text in enumerate(dec_list, start=1):
            conn.execute(
                sa.text(
                    "INSERT INTO project_decisions (id, session_id, project_id, user_id, decision_text, decision_order, created_at, updated_at) VALUES (:id, :session_id, :project_id, :user_id, :text, :order, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
                ),
                {
                    "id": str(uuid.uuid4()),
                    "session_id": r['id'],
                    "project_id": r['project_id'],
                    "user_id": r['user_id'],
                    "text": text,
                    "order": idx,
                },
            )

    # apply remaining autogenerated changes (skip embedding type change on SQLite)
    if conn.dialect.name != 'sqlite':
        op.alter_column('chunks', 'embedding',
                   existing_type=sa.NUMERIC(precision=384),
                   type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
                   existing_nullable=False)

    # drop old JSON column from sessions (after data migrated)
    op.drop_column('sessions', 'decisions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # re-create the JSON column on sessions
    op.add_column('sessions', sa.Column('decisions', sqlite.JSON(), nullable=False, server_default='[]'))

    # (optional) migrate data back from project_decisions into sessions.decisions
    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id FROM sessions")).fetchall()
    for r in rows:
        decs = conn.execute(sa.text("SELECT decision_text FROM project_decisions WHERE session_id = :sid ORDER BY decision_order"), {"sid": r['id']}).fetchall()
        dec_list = [d[0] for d in decs]
        if dec_list:
            conn.execute(sa.text("UPDATE sessions SET decisions = :dec WHERE id = :sid"), {"dec": json.dumps(dec_list), "sid": r['id']})

    # skip reverse embedding type change on SQLite
    conn = op.get_bind()
    if conn.dialect.name != 'sqlite':
        op.alter_column('chunks', 'embedding',
                   existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
                   type_=sa.NUMERIC(precision=384),
                   existing_nullable=False)
    # ### end Alembic commands ###
