"""modified checkpoint_reached field from String to text

Revision ID: 5bab90818e8d
Revises: e7a1b2c3d4f5
Create Date: 2026-06-28 20:22:14.403966

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bab90818e8d'
down_revision: Union[str, Sequence[str], None] = 'e7a1b2c3d4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding',
               existing_type=sa.NUMERIC(precision=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=False)
    op.add_column('memories', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.alter_column('memories', 'embedding',
               existing_type=sa.TEXT(),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    op.create_index(op.f('ix_memories_project_id'), 'memories', ['project_id'], unique=False)
    op.create_foreign_key(None, 'memories', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.alter_column('sessions', 'checkpoint_reached',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'checkpoint_reached',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_index(op.f('ix_memories_project_id'), table_name='memories')
    op.alter_column('memories', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('memories', 'project_id')
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=sa.NUMERIC(precision=384),
               existing_nullable=False)
    # ### end Alembic commands ###
