"""changed embedding column type 2

Revision ID: a95ecd118b35
Revises: 50ef3a1a93fd
Create Date: 2026-04-13 15:17:55.554622

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a95ecd118b35'
down_revision: Union[str, Sequence[str], None] = '50ef3a1a93fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.alter_column('chunks', 'embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=False,
               postgresql_using="embedding::text::vector(384)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
